### ISSUE TITLE
How do I set the camera installed on my turtolbot3 as the first camera in play?

### ISSUE THREAD

**Issue by YuminosukeSato** [rapyuta-robotics/turtlebot3-UE#67]
I want to designate the first camera in play as the camera installed in turtolbot3 in unreal engine 5. However, I have to change the blue print and I don't know which blue print to change. How do I set the camera installed on my turtolbot3 as the first camera in play?

**Comment by yuokamoto** [comment]
please check
https://docs.unrealengine.com/4.26/ja/InteractiveExperiences/UsingCameras/SwitchingCameras/

**Comment by YuminosukeSato** [comment]
I installed the camera, but the camera actor does not appear in the blueprint. And I have to change the blueprint, but I want to connect to ROS2, so when I'm playing while maintaining this state
I want to connect to turtlebot's camera.
![Screenshot from 2023-07-12 12-20-30](https://github.com/rapyuta-robotics/turtlebot3-UE/assets/69001166/4f4b2b2c-a535-4b33-b915-b8f3200c0658)
![Screenshot from 2023-07-12 12-20-43](https://github.com/rapyuta-robotics/turtlebot3-UE/assets/69001166/b9c3ca36-2d3e-4204-92b2-3a3ec8d63a17)

**Comment by yuokamoto** [comment]
you can assign any actor which have camera component as a target

![image (56)](https://github.com/rapyuta-robotics/turtlebot3-UE/assets/16463135/5451b22c-e105-4ddf-94c4-0762f796c7b1)

this is more general question about UE and not related to this repo. you can search more on UE doc and forum.
https://forums.unrealengine.com/t/set-view-target-from-camera-component/311905
