### ISSUE TITLE
Tested with ROS2 Cartographer?

### ISSUE THREAD

**Issue by alexzhang13** [rapyuta-robotics/turtlebot3-UE#71]
Does this repo work with cartographer? I want to map out the environment collected in UE5, but when I follow [this guide](https://ros2-industrial-workshop.readthedocs.io/en/latest/_source/navigation/ROS2-Cartographer.html) but replace any Gazebo portions with the UE5 simulator, no map gets spawned. 

The main difference is that rviz complains about a missing Map frame, but I've noticed this when using nav2 with rviz and it works just fine.

**Comment by yuokamoto** [comment]
I haven't used cartographer. need to investigate what information is misssing from UE.
Do you have list of topic which is required from sim?

**Comment by alexzhang13** [comment]
So I think it's mainly the map/ topic, which is an empty stream when launching cartographer (but it has a subscriber and publisher).

The workaround I have right now is also launching nav2 concurrently, which for some reason (maybe it's because we calibrate pose?) is able to get cartographer to work.
