### ISSUE TITLE
problem in installing rclUE plugin in UE5 trying "Turtlebot3-UE"

### ISSUE THREAD

**Issue by MacBuki** [rapyuta-robotics/turtlebot3-UE#72]
I am learning about connecting UE5 and ROS2 humble.And, I've searched and found your solution, rclUE.But, from the beginning, I got stuck on adding plugin rclUE to unreal.I'm using ubuntu 22.04, UE 5.2.1, ROS2 Humble.As I add the 'rclUE' folder to "/Linux_Unreal_Engine_5.2.1/Engine/Plugins/", It got crashed.Is there another way to add plugin to unreal? Also, before trying "Turtlebot3-UE", What other plugins or setting do I need??

**Comment by yuokamoto** [comment]
you don't need to put project-level plugin to UnrealEngine directory.
you just need to put rclUE under Plugins folder of project like turtlebot3-UE.

Currently our plugins supports UE 5.1 not 5.2 but there maybe a working branch for UE 5.2 cc @Tadinu

**Comment by james-yoo** [comment]
@MacBuki 
I confirm that using the 'UE5.2' branch perfectly works on Ubuntu 22.04, UE5.2.1 and ROS 2 humble.

**Comment by MacBuki** [comment]
@yuokamoto Okay, succeed opening "Turtlebot3-UE".
UE said I have to copy the project, because, the version is not mach. so, I did it.
however, I got tons of errors....
what I got is:
"Turtlebot3-UE"-Jammy
"rclUE"-UE5
"RapyutaSimulationPlugins"-UE5.2

Is the branch what I got is work?

**errors..**
> The summary for the package '/RapyutaSimulationPlugins/Robots/Turtlebot3/Kinematics/BP_TurtlebotBurgerVehicle' is invalid. Check that the file is of the expected type and not corrupted.
> The summary for the package '/RapyutaSimulationPlugins/Robots/Turtlebot3/Kinematics/BP_TurtlebotWaffleVehicle' is invalid. Check that the file is of the expected type and not corrupted.
> The summary for the package '/RapyutaSimulationPlugins/Robots/Turtlebot3/Physics/BP_TurtlebotBurger' is invalid. Check that the file is of the expected type and not corrupted.
> The summary for the package '/RapyutaSimulationPlugins/Robots/Turtlebot3/Physics/BP_TurtlebotWaffle' is invalid. Check that the file is of the expected type and not corrupted.

**Comment by james-yoo** [comment]
@MacBuki 
You should use 'UE5_devel_humble' branch for rclUE plugin

**Comment by MacBuki** [comment]
Okay, trying with
-"Turtlebot3-UE"-Jammy
-"rclUE"-UE5_devel_humble
-"RapyutaSimulationPlugins"-UE5.2

No, crach on playing! yeah!

the example I want to try is "RobotArmExample"
But I think the model is missing?
![Screenshot from 2023-08-11 10-10-47](https://github.com/rapyuta-robotics/turtlebot3-UE/assets/44134072/717ec703-8c3b-48b3-9345-65ef1180752b)
![Screenshot from 2023-08-11 10-15-01](https://github.com/rapyuta-robotics/turtlebot3-UE/assets/44134072/9cc53fa0-0c7c-4c4d-8186-04cb07c27f26)

> 
> Could not find a variable named "ElbowJoint" in 'RobotArmExample'.
> Make sure 'RobotArmExample' has been compiled for  Get ElbowJoint
> Could not find a variable named "ShoulderLiftJoint" in 'RobotArmExample'.
> Make sure 'RobotArmExample' has been compiled for  Get ShoulderLiftJoint
> Could not find a variable named "ShoulderPanJoint" in 'RobotArmExample'.
> Make sure 'RobotArmExample' has been compiled for  Get ShoulderPanJoint
> Node  Unknown  is not referencing a valid level actor
> The property associated with  Elbow Joint  could not be found in '/Game/Maps/RobotArmExample.RobotArmExample_C'
> The property associated with  Shoulder Lift Joint  could not be found in '/Game/Maps/RobotArmExample.RobotArmExample_C'
> The property associated with  Shoulder Pan Joint  could not be found in '/Game/Maps/RobotArmExample.RobotArmExample_C'

**Comment by yuokamoto** [comment]
Since UE5.2 branch is created before robot arm examples are added.
I created branch with rebase from devel. please try it 
https://github.com/rapyuta-robotics/RapyutaSimulationPlugins/tree/UE5.2_rebase

**Comment by MacBuki** [comment]
Okay, trying with
-"Turtlebot3-UE"-Jammy
-"rclUE"-UE5_devel_humble
-"RapyutaSimulationPlugins"-UE5.2_rebase

I've checked that the file is invalid?
![Screenshot from 2023-08-17 13-02-36](https://github.com/rapyuta-robotics/turtlebot3-UE/assets/44134072/473e047b-3819-4594-a3c0-2ebed03fb40f)
![image](https://github.com/rapyuta-robotics/turtlebot3-UE/assets/44134072/b112eae5-9f6c-4e74-a3b3-2151be4bf536)




>  The summary for the package '/RapyutaSimulationPlugins/Robots/SampleArm/BP_KinematicSimpleArm' is invalid. Check that the file is of the expected type and not corrupted.
> The summary for the package '/RapyutaSimulationPlugins/Robots/UR10/BP_KinematicUR10' is invalid. Check that the file is of the expected type and not corrupted.
> The summary for the package '/RapyutaSimulationPlugins/Robots/UR10/BP_PhysicsUR10' is invalid. Check that the file is of the expected type and not corrupted.

**Comment by yuokamoto** [comment]
Did you git lfs pull? it maybe not pulled properly.

**Comment by yuokamoto** [comment]
Please reopen if issue still exists
