### ISSUE TITLE
undefined symbol: rmw_time_equal

### ISSUE THREAD

**Issue by kpwelsh** [rapyuta-robotics/turtlebot3-UE#79]
Hi, 

I am trying to run this project with ROS2-Humble on Ubuntu-22.04 with UE5.1. Everything is a fresh install.

It seems that I have almost gotten it to run, but when I try to launch this project, I receive the following error:

```
symbol lookup error: /opt/ros/humble/lib/librmw_fastrtps_shared_cpp.so: undefined symbol: rmw_time_equal
``` 

Perhaps unrelated, but also whenever I make the editor I can no longer run "fastdds discovery -i 0" until I restart. That yields:

```
024-01-31 17:00:43.854 [RTPS_PARTICIPANT Error] Discovery Server wasn't able to allocate the specified listening port. -> Function createParticipant
Server creation failed with the given settings. Please review locators setup.
2024-01-31 17:00:43.856 [DOMAIN_PARTICIPANT Error] Problem creating RTPSParticipant -> Function enable
fastdds discovery <discovery-args>

1
 fast-discovery-server tool not found!
```

Any tips would be appreciated :).

**Comment by kpwelsh** [comment]
Nevermind. 

I had a mismatch of branches checked out. Getting messages now.

**Comment by arjuntheprogrammer** [comment]
@kpwelsh - can you please mention the branch you used for all three repos:
1. turtlebot3-UE
2. rclue
3. RapyutaSimulationPlugins

I ran into the same issue: https://github.com/rapyuta-robotics/turtlebot3-UE/issues/92

I just checkout into humble branch for turtlebot3-UE repository
