### ISSUE TITLE
How to publish the ROS2 topic /clock from the Unreal simulation time?

### ISSUE THREAD

**Issue by maitelorente** [rapyuta-robotics/turtlebot3-UE#81]
Hi,

I would like to know how to publish the topic /clock in ROS2 from the Unreal simulation time. I have seen that the turtlebot3 example publishes the topic /clock and that other topics, like the topic /points, also include the timestamp accordingly. However, I have not been able to find where and how it is done in the code provided, neither with the blueprints nor in the cpp code. Please, could you give me advise on this matter?

Thank you in advance!

**Comment by yuokamoto** [comment]
Hi,

Here is ClockPublisher class
https://github.com/rapyuta-robotics/RapyutaSimulationPlugins/blob/devel/Source/RapyutaSimulationPlugins/Private/Tools/RRROS2ClockPublisher.cpp

And it is used from GameMode
 https://github.com/rapyuta-robotics/RapyutaSimulationPlugins/blob/292b60a272db4ee2cf618673c47db9e27a0b5b7d/Source/RapyutaSimulationPlugins/Private/Core/RRROS2GameMode.cpp#L133
