### ISSUE TITLE
spawn all asset is not working.

### ISSUE THREAD

**Issue by Kim-YoungJ** [rapyuta-robotics/turtlebot3-UE#84]
I am using ubuntu 22.04 (jammy) and Unreal Engine 5.1.1. i follow description in readme.  Then working fine world map which i use turtlebot3 benchmark. However, the turtlebot3 does not spawn it. In Unreal engine log massage says that BP_TurtlebotBuger is invalid. take a look picture. 
What should i do? can you help this problem?
![Screenshot from 2024-04-12 09-23-00](https://github.com/rapyuta-robotics/turtlebot3-UE/assets/98382528/624b7c7e-71b9-4b5c-b626-cc4ae2aed1b2)

**Comment by yuokamoto** [comment]
Hello,
- Are you using `jammy` branch of turtlebot3-UE? Could you try `git submodule update --init --recursive`?
- Did you do git-lfs pull? This can happen if large binary are not pulled.

**Comment by Kim-YoungJ** [comment]
@yuokamoto  Thanks a lot. i solved it using git-lfs pull, the large binary files are not pulled as you mentioned.
