### ISSUE TITLE
fram_id modification required to run example Ubuntu 22.04 Humble

### ISSUE THREAD

**Issue by KMerdan** [rapyuta-robotics/turtlebot3-UE#89]
## Description

I am following the documentation to run the `jammy` branch of `turtlebot3-UE`. However, the `turtlebot3-UE` publisher automatically adds the `BP_TurtlebotWaffle` prefix to the `frame_id` & `topic_name` of the published topics. For example:

- `/BP_TurtlebotWaffle/odom`
- `/BP_TurtlebotWaffle/base_scan`
- `/BP_TurtlebotWaffle/base_link`

This is causing issues because `nav2` expects these frames without the prefix (e.g., `odom`, `base_scan`, `base_link`).

## Expected Behavior

I would like to know how to remove or customize the `BP_TurtlebotWaffle` prefix in `turtlebot3-UE` so that the frame IDs are published without it.

For example:

- `/odom` instead of `/BP_TurtlebotWaffle/odom`
- `/base_scan` instead of `/BP_TurtlebotWaffle/base_scan`
- `/base_link` instead of `/BP_TurtlebotWaffle/base_link`

## Additional Information

I am not very familiar with Unreal Engine Blueprints and have mainly been looking at the code. However, I haven't found anything in the source code that directly relates to this issue. It would be helpful if someone could point me in the right direction or suggest how to modify this behavior.

**Comment by yuokamoto** [comment]
Hi,
Thanks for you comment ans sorry for late response.

Could you try
- setting bUseActorNameAsNamespace = false
https://github.com/rapyuta-robotics/RapyutaSimulationPlugins/blob/9dce510b48a16122855d48c18032741708a305d3/Source/RapyutaSimulationPlugins/Public/Robots/RRBaseROS2Interface.h#L75

**Comment by KMerdan** [comment]
Thanks, that works.
a little bit off the topic, i still have trouble to run the turtleBot3-UE example with nav2 stack like this:
`ros2 launch nav2_bringup tb3_simulation_launch.py use_simulator:=False map:=./Content/Turtlebot3_benchmark.yaml`
where the tf between `map` and `odom` are not been published(by acml i guess), 
![image](https://github.com/user-attachments/assets/2694f31a-6e72-4441-ad76-90df762caeef)
so it results like this
![Screenshot from 2024-10-02 14-08-35](https://github.com/user-attachments/assets/85aa30a4-e205-4e29-ac71-17a8a9440315)

any idea what i missed here @yuokamoto

**Comment by yuokamoto** [comment]
I'll check later
Did you provide initial pose?

**Comment by KMerdan** [comment]
yes, i did.

**Comment by james-yoo** [comment]
@KMerdan
I think 'wheel_right' and 'wheel_left' link should be attached to 'base_link' not 'base'.

**Comment by KMerdan** [comment]
@james-yoo i think you are right. but this is what `turtleBot3-UE` default publish result, i didn't do any modification yet, just try to run it.

**Comment by yuokamoto** [comment]
Sorry for late
- I updated jammy branch. Could you try?
- I attached video with the branch.

https://github.com/user-attachments/assets/137b0ac9-d8a8-424a-96bd-4d171d4886e0

[frames_2024-10-08_23.26.27.pdf](https://github.com/user-attachments/files/17294891/frames_2024-10-08_23.26.27.pdf)

**Comment by KMerdan** [comment]
Confirmed here, works like a charm. Thanks.
@yuokamoto

**Comment by yuokamoto** [comment]
Thanks for your reporting
